export const REWARDS = {
  WIN_BEANS: 100,
  LOSE_BEANS: 20,
  DRAW_BEANS: 50,
  STREAK_BONUS_BEANS: 30,
  WIN_RANK_SCORE: 30,
  LOSE_RANK_SCORE: -10,
  DRAW_RANK_SCORE: 5,
  DAILY_TICKETS: 3,
} as const;
